### ISSUE TITLE
Better UI for Checkbox

### ISSUE THREAD

**Issue by inoex135** [laravolt/semantic-form#16]
I don't like the result of checkbox, this is not pretty
![image](https://user-images.githubusercontent.com/244285/48963901-e4c22e80-efcf-11e8-9d08-a47ac8a083f2.png)

Can we have better ui for this one?

**Comment by uyab** [comment]
I believe your are not using SemanticForm to generate the checkbox.

The result should look like this:

```php
SemanticForm::checkboxGroup('name', $values, $checkedValue)->label('Select Fruit');
```
![image](https://user-images.githubusercontent.com/149716/48963984-65355f00-efd1-11e8-9305-e3c05a595aab.png)
