### ISSUE TITLE
Route show not defined 

### ISSUE THREAD

**Issue by anandiamy** [laravolt/semantic-form#19]
When I except show method in route, it shows an error

![image](https://user-images.githubusercontent.com/8675936/59729749-0899da00-926a-11e9-96f9-dc7d6dfef629.png)

My route :
`Route::resource('saas', 'SaasController')->except(['show']);`

My suitable column :
`RestfulButton::make('saas')->only(['edit', 'delete'])`

**Comment by uyab** [comment]
Fixed in 2.2.1
