### ISSUE TITLE
readonly not work on select multiple

### ISSUE THREAD

**Issue by anandiamy** [laravolt/semantic-form#21]
readonly not work on selectMultiple even though using the method **->readonly ()** or **->attribute('readonly', 'readonly')**

**Comment by uyab** [comment]
@anandiamy can you provide full sample code and the HTML generated by selectMultiple? Does it contains attribute readonly or not?

**Comment by uyab** [comment]
Semantic UI doesn't support readonly for dropdown. You can use `disable()`, althought it will have different look.
