### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by mohamedsabil83** [laravolt/semantic-form#7]
There is missing class in the following:

- When using `->required()` with `->input()` the **red asterisk** doesn't appear in the label.
- In **error**, `->input()` doesn't color as red like other type eg. `->text()`, `->password()` ...etc.

**Comment by uyab** [comment]
Fixed in 1.10.5.

Note: If you place your input inside `ui form`, then the red styling will not appear. You must add class `field` manually to your input wrapper.
